#include "avr/pgmspace.h"

const char s1[] PROGMEM = "Aluminiumfolie reißt nicht so leicht, wenn man sie vor Gebrauch vollflächig auf Rigipsplatten klebt.";
const char s2[] PROGMEM = "Bier hinterlässt keine Rotweinflecken.";
const char s3[] PROGMEM = "Die Wohnung bleibt beim Bohren von Dübellöchern staubfrei, wenn Sie die Wand vorher in den Garten tragen.";
const char s4[] PROGMEM = "Kleine Brandlöcher entfernt man am besten mit einer Nagelschere.";
const char s5[] PROGMEM = "Brot trocknet nicht aus, wenn man es in einem Eimer mit Wasser lagert.";
const char s6[] PROGMEM = "Fettflecken halten länger, wenn man sie ab und zu mit Butter einreibt.";
const char s7[] PROGMEM = "Salzflecken auf einer Tischdecke bekommt man mit etwas Rotwein wieder heraus.";
const char s8[] PROGMEM = "Rhabarberkompott schmeckt noch besser, wenn man statt Rhabarber Erdbeeren nimmt.";
const char s9[] PROGMEM = "Tränen beim Zwiebelschneiden kann man vermeiden, indem man die Zwiebel durch eine Kohlrabi ersetzt.";
const char s10[] PROGMEM = "Spinat schmeckt erheblich besser, wenn man ihn kurz vor dem Servieren duch ein saftiges Steak ersetzt.";
const char s11[] PROGMEM = "Heißes Wasser braucht man andauernd in der Küche. Deshalb sollte man sich einen kleinen Vorrat davon einfrieren.";
const char s12[] PROGMEM = "Neue Wasserkocher verkalken nicht so schnell, wenn man sein Wasser weiterhin im alten kocht...";
const char s13[] PROGMEM = "Stockflecken in Gartenmöbelauflagen verschwinden, wenn man Ketchup drübergießt.";
const char s14[] PROGMEM = "Kaffeefilter sollte man höchstens dreimal wiederverwenden, es lohnt die Mühe, nach dem 3. Mal frischen Kaffee zu malen.";
const char s15[] PROGMEM = "Messer werden richtig scharf, wenn man Tabasco drauf gießt.";
const char s16[] PROGMEM = "Schmutziges Geschirr schimmelt nicht, wenn es in der Tiefkühltruhe aufbewahrt wird.";
const char s17[] PROGMEM = "Bratkartoffeln werden unvergleichlich kross, wenn man sie beim im Internetstöbern in der Pfanne vergisst.";
const char s18[] PROGMEM = "Fisch wird besonders zart, wenn man ihn vor der Zubereitung, ein paar Tage herum stehen lässt.";
const char s19[] PROGMEM = "Kartoffeln werden herrlich weich, wenn man zum Kochen ein bisschen Wasser zugibt.";
const char s20[] PROGMEM = "Versalzene Suppen schmecken gleich ganz anders, wenn man sie gekonnt anbrennen lässt.";
const char s21[] PROGMEM = "Zu Zwiebel- Kräuterquark und Pellkartoffeln, passt wunderbar Dorschleber in Vanillesoße.";
const char s22[] PROGMEM = "Köche verderben nicht nur den Brei, sie können im Prinzip alle Speisen versauen, wenn man sie höflich darum bittet.";
const char s23[] PROGMEM = "Volle Abfallsäcke erkennt man daran, dass sich der Abfalleimer nicht mehr schließen lässt, sich Millionen von kleinen Mücken sich auf das Butterbrot stürzen und der Platzwart stündlich nach Todesfällen fragt. Abhilfe schafft man, indem man den Müll in den Kühlschrank steckt.";
const char s24[] PROGMEM = "Mit Senf oder Zahnpasta verschmierte Türklinken lassen sich mittels bromsaurem Radiumbikarbonat mühelos reinigen.";
const char s25[] PROGMEM = "Sticke deinen Vornamen in schwarz auf dein weißes Hemd. Du weißt dann immer, wenn es gewaschen werden muß. Nämlich dann, wenn du deinen Namen nicht mehr lesen kannst. Dieser Trick funktioniert auch mit anderen Farben!";
const char s26[] PROGMEM = "Sollte nach einem Lager beim Waschen der Wäsche diese absolut nicht weiß werden, könnte es sich um Buntwäsche handeln.";
const char s27[] PROGMEM = "Milch bleibt wesentlich länger frisch, wenn man sie in der Kuh belässt.";
const char s28[] PROGMEM = "Hundert-Euro- und andere Geldscheine, die man des öfteren auf der Straße findet, eignen sich hervorragend dazu, die Löcher in der Geldbörse zu stopfen.";
const char s29[] PROGMEM = "Falls Sie Kettenbriefe in der Post finden, denken Sie daran: Nur die Briefe kommen ins Altpapier, die Ketten kommen in die gelbe Tonne.";
const char s30[] PROGMEM = "Weizenbier lässt sich leichter einschenken, wenn man statt Reis ein kleines Seifestück ins Glas tut.";
const char s31[] PROGMEM = "Knäckebrot krümelt nicht mehr, wenn man es kurz vor dem Verzehr in eine Schale lauwarmes Wasser legt. ";
const char s32[] PROGMEM = "Zwiebeln statt Kiwis kaufen! Sie sind länger haltbar und außerdem länger haltbar.";
const char s33[] PROGMEM = "Umwickeln Sie Ihre Glühbirnen doppelt mit Tesafilm. So gibt es keine Scherbenexplosion, falls die Birne aus irgendeinem Grund aus dem Gewinde fallen sollte.";
const char s34[] PROGMEM = "Katzensand im Badezimmer mindert eindeutig die Rutschgefahr. So werden Unfälle während und nach dem Duschen verhindert.";
const char s35[] PROGMEM = "Schmutziges Geschirr schimmelt nicht, wenn man es in der Gefriertruhe aufbewahrt.";
const char s36[] PROGMEM = "Je mehr Käse desto mehr Löcher, je mehr Löcher, desto weniger Käse! Fazit: Je mehr Käse, desto weniger Käse!";
const char s37[] PROGMEM = "Koche Wasser nach Celsius, nicht mehr nach Fahrenheit. Das spart 112 Grad und ist somit gut für die Umwelt.";
const char s38[] PROGMEM = "Teigwaren heißen Teigwaren, weil Teigwaren mal Teig waren.";
const char s39[] PROGMEM = "Zucker ist der Stoff, der dem Kaffee den schlechten Geschmack gibt, wenn man vergisst, ihn reinzutun.";
const char s40[] PROGMEM = "Mit einer Scheibe Salami in der Achselhöhle erstrahlen Schweißränder im Sommer in einem wunderschönen Rot.";
const char s41[] PROGMEM = "Hab Sonne im Herzen und Zwiebeln im Bauch, dann kannst du gut Ferzen und stinken tuts auch.";
const char s42[] PROGMEM = "Kräht der Hahn auf dem Mist, ändert sich das Wetter oder bleibt wie es ist.";
const char s43[] PROGMEM = "Es ist auf jeden Fall besser heimlich schlau zu sein, als unheimlich blöd.";
const char s44[] PROGMEM = "Hast du Zahnpasta im Ohr,kommt dir alles leise vor";
const char s45[] PROGMEM = "Nem geschenkten Barsch guckt man nicht hinter die Kiemen.";
const char s46[] PROGMEM = "Atmen durch den Hintermund, hält Leib und Seele gesund.";
const char s47[] PROGMEM = "Bohnen, Erbsen und auch Linsen bringens Ärschle schnell zum Grinsen!";
const char s48[] PROGMEM = "Aftershave ist nicht das Gegenteil von Mundwasser!";
const char* const advices[] PROGMEM = {s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24,s25,s26,s27,s28,s29};
String getAdvice(){
    char stringBuffer[275];
    randomSeed(millis());
    int randomNum = random(0,47);
    Serial.println("Random: " + String(randomNum));
 strcpy_P(stringBuffer, (char*)pgm_read_word(&(advices[randomNum])));
  return String(stringBuffer);
}
